Method uses `generics`, `abc property`, and `abc method`
execution-flows/fy pull request #429
Opened 2024-12-20 23:21 UTC by PerisicJere

2024-12-20 23:41 UTC, vinkobuble approved these changes

2024-12-20 23:41 UTC, vinkobuble commented on library/src/fy_library/mixins/property/generated_fy_py_code/jinja2_templates/method.jinja2
> +{%- if abstract_property_mixins or  abstract_method_mixins or generics_def-%}
```suggestion
{%- if abstract_property_mixins or  abstract_method_mixins or generics_def -%}
```

2024-12-21 13:57 UTC, vinkobuble requested changes

2024-12-21 13:57 UTC, vinkobuble commented on library/tests/fy_py_files/test_fy_py_files/method_with_generics_impl/method_with_generics_impl_fy.py
> +    property french_greeting[FrenchGreeting]
```suggestion
    property greeting[FrenchGreeting]
```

2024-12-21 13:57 UTC, vinkobuble commented on library/tests/fy_py_files/test_fy_py_files/method_with_generics_impl/abc_property/abc_fy.py
> +property french_greeting: FrenchGreeting
```suggestion
property greeting[GreetingT]:
```

2024-12-21 17:06 UTC, PerisicJere commented on library/src/fy_library/mixins/property/generated_fy_py_code/jinja2_templates/method.jinja2
> +{%- if abstract_property_mixins or  abstract_method_mixins or generics_def-%}
Changed

2024-12-21 17:06 UTC, PerisicJere commented on library/tests/fy_py_files/test_fy_py_files/method_with_generics_impl/method_with_generics_impl_fy.py
> +    property french_greeting[FrenchGreeting]
Changed

2024-12-21 17:06 UTC, PerisicJere commented on library/tests/fy_py_files/test_fy_py_files/method_with_generics_impl/abc_property/abc_fy.py
> +property french_greeting: FrenchGreeting
changed

2024-12-21 17:38 UTC, vinkobuble approved these changes

2024-12-21 17:41 UTC, merged